name: CI

on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r module8_is601/requirements.txt
          python -m playwright install --with-deps

      - name: Run unit & integration tests
        run: |
          pytest module8_is601/tests/test_operations_unit.py module8_is601/tests/test_api_integration.py

      - name: Run end-to-end tests (Playwright)
        run: |
          pytest module8_is601/tests/e2e/test_e2e_ui.py