name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install --with-deps

      - name: Run unit & integration tests
        run: |
          pytest -q tests/test_operations_unit.py tests/test_api_integration.py

      - name: Run end-to-end tests (Playwright)
        run: |
          pytest -q tests/e2e/test_e2e_ui.py
