name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install --with-deps

      - name: Run unit tests
        run: |
          pytest -q tests/unit/ --cov=app --junitxml=test-results/junit.xml

      - name: Run integration tests
        run: |
          pytest -q tests/integration/

      - name: Run end-to-end tests (Playwright)
        run: |
          pytest -q tests/e2e/test_e2e.py
